/**
 * Drive Rename + Move  --  generated by the file-namer / drive-organizer skills.
 *
 * WHY THIS SCRIPT EXISTS
 * Claude can read and search your Google Drive and create files, but the Drive
 * connection has NO rename, move, or delete. This script does the rename and the
 * move for you, IN PLACE, so every file/folder keeps its original ID and link --
 * rename hundreds of items and none of your existing links break.
 *
 * IT HANDLES FILES *AND* FOLDERS. Add  isFolder: true  to a row to rename/move a
 * folder (its contents move with it). This is built for BULK cleanups: point
 * ROOT_FOLDER_ID at a HIGH parent folder so one run can sweep many files and
 * subfolders at once.
 *
 * HOW TO RUN (Claude normally drives this for you in the browser; manual = below)
 * 1. https://script.google.com/home/projects/create -> delete sample -> paste -> Save.
 * 2. In the function dropdown choose "organizeDrive".
 * 3. Run (ships with DRY_RUN = false = apply directly). Approve the one-time Google
 *    permission prompt (Advanced -> Go to project -> Allow). It applies + verifies; done
 *    at "Finished". The skill writes a memory index of every change so anything can be
 *    reverted. Set DRY_RUN = true only if you want a no-change preview first.
 *
 * Claude fills the four sections marked FILLED IN BY CLAUDE.
 */

// =========================== FILLED IN BY CLAUDE ============================

var DRY_RUN = false;                 // true = preview only; false = apply.
var ROOT_FOLDER_ID = "PASTE_ROOT_FOLDER_ID";  // a HIGH parent folder for bulk runs.
var BACKUP_ENABLED = false;         // true = copy each FILE to _Backup-Original first.

// Skeleton folders to ensure exist (use "/" between levels).
var FOLDERS = [
  // "01_Legal", "02_Finance", "02_Finance/Lending", "03_Operations",
  // "04_Properties", "05_Archive"
];

// One row per item to rename and/or move.
//   fileId    = the Drive ID of the file OR folder (Claude supplies it)
//   newName   = new name (leave "" to keep current name)
//   destPath  = where to move it, relative to ROOT, "/" between levels (leave "" = stay)
//   isFolder  = true for a FOLDER (omit/false for a file)
var OPERATIONS = [
  // { fileId: "1AbC...", newName: "SignedLease-v1-Doe-123MAIN-LEASE-06092026.pdf",
  //   destPath: "04_Properties/123 Main St/Leasing/Doe/02_Lease" },
  // { fileId: "1FoLDeR...", newName: "04_Properties", destPath: "", isFolder: true },
];

// ============================================================================

function organizeDrive() {
  var root = DriveApp.getFolderById(ROOT_FOLDER_ID);
  Logger.log(DRY_RUN ? ">>> DRY RUN (preview only, nothing will change) <<<"
                     : ">>> LIVE RUN (renaming + moving for real) <<<");

  for (var f = 0; f < FOLDERS.length; f++) {
    var path = FOLDERS[f];
    if (DRY_RUN) { Logger.log((folderExistsByPath(root, path) ? "exists  " : "CREATE  ") + path); }
    else { getOrCreateFolderByPath(root, path); Logger.log("folder ready  " + path); }
  }

  var backup = (!DRY_RUN && BACKUP_ENABLED) ? getOrCreateChild(root, "_Backup-Original") : null;

  var done = 0, failed = 0, wouldDo = 0;
  for (var i = 0; i < OPERATIONS.length; i++) {
    var op = OPERATIONS[i];
    var kind = op.isFolder ? "folder" : "file";
    try {
      var item = op.isFolder ? DriveApp.getFolderById(op.fileId)   // folders supported
                             : DriveApp.getFileById(op.fileId);
      var curName = item.getName();
      var newName = (op.newName && op.newName !== "") ? op.newName : curName;
      var destTxt = (op.destPath && op.destPath !== "") ? op.destPath : "(stays put)";

      if (DRY_RUN) {
        Logger.log("WOULD " + kind + "  [" + curName + "]  ->  [" + newName + "]   dest: " + destTxt);
        wouldDo++; continue;
      }

      if (backup && !op.isFolder) { item.makeCopy("BACKUP - " + curName, backup); }
      if (op.newName && op.newName !== "") { item.setName(op.newName); }
      if (op.destPath && op.destPath !== "") {
        var dest = getOrCreateFolderByPath(root, op.destPath);
        item.moveTo(dest);                                   // keeps the same ID/link
        var parents = item.getParents();
        var landed = parents.hasNext() ? parents.next().getName() : "(none)";
        Logger.log(((landed === dest.getName()) ? "OK   " : "CHECK") + " " + kind + "  " +
                   item.getName() + "  in [" + landed + "]  " + item.getUrl());
      } else {
        Logger.log("OK   renamed " + kind + "  " + item.getName() + "  " + item.getUrl());
      }
      done++;
    } catch (e) { Logger.log("ERR  " + kind + " " + op.fileId + "  :  " + e); failed++; }
  }

  Logger.log(DRY_RUN ? ("Preview complete. " + wouldDo + " ops would run. Set DRY_RUN = false and Run again to apply.")
                     : ("Finished. " + done + " done, " + failed + " failed."));
}

function folderExistsByPath(root, path){var p=path.split("/"),c=root;for(var i=0;i<p.length;i++){var n=p[i].trim();if(n==="")continue;var it=c.getFoldersByName(n);if(!it.hasNext())return false;c=it.next();}return true;}
function getOrCreateFolderByPath(root, path){var p=path.split("/"),c=root;for(var i=0;i<p.length;i++){var n=p[i].trim();if(n==="")continue;c=getOrCreateChild(c,n);}return c;}
function getOrCreateChild(parent,name){var it=parent.getFoldersByName(name);return it.hasNext()?it.next():parent.createFolder(name);}
